name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: go run
        run: go run main.go

      - name: go build
        run: go build -tags 'netgo' -o cgo-app-netgo main.go

      - name: Save built app
        uses: actions/upload-artifact@v3
        with:
          name: cgo-app-netgo
          path: cgo-app-netgo
          if-no-files-found: error